---
- name: Install required packages
  apt:
    name:
      - postgresql
      - libpq-dev
    state: present
  become: True

- name: Do not run postgresql on startup (run it in Docker instead)
  systemd:
    enabled: no
    name: postgresql
    state: stopped
  become: True