---
- name: Install required apt packages
  apt: name=golang state=present
  become: True

- name: Clone direnv
  git: repo=https://github.com/zimbatm/direnv dest="{{home_dir}}/src/direnv"

- name: Install direnv
  shell: make install chdir={{home_dir}}/src/direnv creates=/usr/local/bin/direnv
  become: True

- name: Add direnv hook
  template: src=direnv.zsh dest={{home_dir}}/.zsh.after/direnv.zsh

- name: Cleanup direnv files
  file:
    path: "{{home_dir}}/src/direnv"
    state: absent
  become: True