---
- name: Install required packages
  apt:
    name:
      - direnv
    state: present
  become: True

- name: Add direnv hook
  template:
    src: direnv.zsh
    dest: "{{home_dir}}/.zsh.after/direnv.zsh"
