---
- name: install required apt packages
  apt: name={{item}} state=present
  become: True
  with_items:
    - tmux
    - zsh
    - git

- name: clone prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git recursive=yes dest="{{home_dir}}/.zprezto"

- name: zsh facts
  shell: 'echo $SHELL'
  register: default_shell
  # changed when determines when will this task be considered changed when running
  # ansible. In this case, we want it to always be false, as we are just
  # retrieving information.
  changed_when: False
  become: no

- name: make zsh default
  user: name={{username}} shell=/bin/zsh
  become: True

- name: copy zsh files
  shell: ln -s {{home_dir}}/.zprezto/runcoms/{{item}} {{home_dir}}/.{{item}} creates={{home_dir}}/.{{item}}
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc

- name: copy tmux config
  copy: "src=tmux.conf dest={{home_dir}}/.tmux.conf"

- name: extract fasd
  unarchive: src="clvv-fasd-1.0.1-0-g4822024.tar.gz" dest="{{home_dir}}"

- name: symlink fasd dir
  file: src="{{fasd_dest_dir}}" dest="fasd" state=link

- name: copy zshrc
  copy: src=zshrc dest={{home_dir}}/.zshrc

- name: Create .zsh.after dir
  file: path={{home_dir}}/.zsh.after state=directory
