---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: True

- apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google.list
  become: True

- name: Install google-chrome-stable
  apt:
    update_cache: yes
    name:
      - google-chrome-stable
    state: present
  become: True
