---
- name: Install required packages to build
  apt:
    name:
      - libssl-dev
      - autoconf
      - automake
      - libtool
      - python-dev
    state: present
  become: True

- name: Clone
  git:
    repo: https://github.com/facebook/watchman.git
    dest: "{{home_dir}}/watchman"
    version: v4.9.0

- name: Prepare for make
  shell:
    cmd: |
      ./autogen.sh
      ./configure
    chdir: "{{home_dir}}/watchman"

- name: Make
  shell:
    cmd: make
    chdir: "{{home_dir}}/watchman"

- name: Install
  shell:
    cmd: make install
    chdir: "{{home_dir}}/watchman"
  become: True

- name: Copy executable
  copy:
    src: "{{home_dir}}/watchman/watchman"
    dest: /usr/local/bin/watchman
    remote_src: yes
  become: True
